# Generated by Django 5.1.3 on 2024-11-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                ("reward_id", models.AutoField(primary_key=True, serialize=False)),
                ("points", models.IntegerField(unique=True)),
                (
                    "reward_date_timestamp",
                    models.CharField(max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("loyalty_score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LoyaltyPoint",
            fields=[
                ("points_id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=300)),
                (
                    "loyalty_reward",
                    models.ForeignKey(
                        db_column="LoyaltyRewards_RewardID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards_app.reward",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(null=True)),
                (
                    "loyalty_point",
                    models.ForeignKey(
                        db_column="LoyaltyPoints_PointsID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards_app.loyaltypoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_User_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                ("redemption_id", models.AutoField(primary_key=True, serialize=False)),
                ("redemption_date", models.DateField(null=True)),
                (
                    "loyalty_reward",
                    models.ForeignKey(
                        db_column="LoyaltyRewards_RewardID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_redemptions",
                        to="rewards_app.reward",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        db_column="Rewards_reward_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="rewards_app.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_User_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards_app.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reward",
            name="user",
            field=models.ForeignKey(
                db_column="User_User_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="rewards_app.user",
            ),
        ),
        migrations.CreateModel(
            name="LoyaltyRewards",
            fields=[
                ("reward_id", models.AutoField(primary_key=True, serialize=False)),
                ("reward_description", models.CharField(max_length=300)),
                ("points_required", models.IntegerField()),
                ("redemption_date", models.DateField(null=True)),
                ("points", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="User_User_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rewards_app.user",
                    ),
                ),
            ],
        ),
    ]
