# Generated by Django 5.1.3 on 2024-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="1", max_length=255),
        ),
    ]
