# Generated by Django 5.1.3 on 2024-11-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="123", max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="loyalty_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
