# Generated by Django 5.1.3 on 2024-11-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0006_remove_transaction_loyalty_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="coupon",
            field=models.CharField(default="1", max_length=10),
        ),
    ]
