# Generated by Django 5.1.3 on 2024-11-21 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0007_transaction_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardredemption",
            name="loyalty_reward",
        ),
        migrations.RemoveField(
            model_name="rewardredemption",
            name="reward",
        ),
        migrations.RemoveField(
            model_name="rewardredemption",
            name="user",
        ),
        migrations.DeleteModel(
            name="LoyaltyPoint",
        ),
        migrations.DeleteModel(
            name="RewardRedemption",
        ),
    ]
