# Generated by Django 5.1.3 on 2024-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0008_remove_rewardredemption_loyalty_reward_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(default="task", max_length=100)),
                ("task_description", models.CharField(max_length=300)),
                ("points", models.IntegerField(unique=True)),
            ],
        ),
    ]
