# Generated by Django 5.1.3 on 2024-11-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rewards_app", "0009_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="points",
            field=models.IntegerField(),
        ),
    ]
